name: Infra Provision Plan
on:
  pull_request:
    branches: [ "main" ]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  
jobs:
  provision-infra:
    runs-on: ubuntu-latest
    steps:
# setup aws iam role for assume role    
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: samplerolesession
          aws-region: ${{secrets.AWS_REGION}}
# setup terraform process with init,validate,plan with backend config          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        with:
          terraform_wrapper: false
      - name: Terraform plan
        id:   plan

        run: |
         terraform init \
           -backend-config="bucket=${{secrets.TF_REMOTE_STATE_BUCKET}}" \
           -backend-config="region=${{secrets.AWS_REGION}}" \
           -backend-config="key=main/terraform.tfstate"
         terraform validate
         terraform plan 
         
