name: Infra Destroy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

env:
  BRANCH_NAME: ${{ github.event.inputs.branch || 'main' }}

permissions:
  id-token: write
  contents: read

jobs:
  infra-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: samplerolesession
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        with:
          terraform_wrapper: false

      - name: Terraform Destroy
        id: destroy
        run: |
          terraform init \
           -backend-config="bucket=${{secrets.TF_REMOTE_STATE_BUCKET}}" \
           -backend-config="region=${{secrets.AWS_REGION}} \
           -backend-config="key=main/terraform.tfstate"
          terraform validate
          terraform destroy --var="aws_region=${{secrets.AWS_REGION}}" --auto-approve
